var ATIV_INICIAL = 0;
var ATIV_REGISTRAR_CHAMADO = 4;
var ATIV_ANALISAR_CHAMADO = 9;
var ATIV_ATENDER_CHAMADO = 13;
var ATIV_APROVAR_CHAMADO = 30;
var ATIV_TRATAR_CHAMADO = 19;
var ATIV_FINALIZAR_CHAMADO = 26;
var ATIV_FIM = 28;


//var ATIV_ACIONAR_PRESTADOR = 36;